version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: task_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-api-container
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - mysql
    env_file:
      - .env.docker
    volumes:
      - .:/var/www/html
      - ./.env.docker:/var/www/html/.env:ro
volumes:
  db_data:
