version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: task_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-api-container
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: task_db
      DB_USERNAME: root
      DB_PASSWORD: secret
    volumes:
      - .:/var/www/html
volumes:
  db_data:
