version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: task_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-api-container
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      DB_CONNECTION=pgsql
      DB_HOST=dpg-d2dccfruibrs739gg7cg-a
      DB_PORT=5432
      DB_DATABASE=api_4qbn
      DB_USERNAME=root
      DB_PASSWORD=QxdQ0DPSxMRghYyli5bJIpmCHySlJjXo
    volumes:
      - .:/var/www/html
volumes:
  db_data:
